# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('tariff_id', models.AutoField(primary_key=True, serialize=False)),
                ('tariff', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'tariff',
            },
        ),
        migrations.CreateModel(
            name='UserConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnsmpt_date', models.DateTimeField()),
                ('consumption', models.FloatField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_consumption',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.Area')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.Tariff')),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
        migrations.AddField(
            model_name='userconsumption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.UserData', to_field='user_id'),
        ),
    ]
